import pandas as pd 


import matplotlib.pyplot as plt

df = pd.read_csv("global_ecommerce_sales.csv")
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

# print(df.shape)
# print(df.columns)
# print(df.info())
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate Order IDs:", df['Order_ID'].duplicated().sum())
print("Total Sales:", df['Total_Sales'].sum())
print("TOtal Profit:'", df['Profit'].sum())
print("Total Quantity:'", df['Quantity'].sum())
print("Total Orders:'", df['Order_ID'].nunique())

category_sales = df.groupby('Product_Category')['Total_Sales'].sum().sort_values(ascending=False)
print("\nCategory-wise Sales:")
print(category_sales)

category_profit = df.groupby('Product_Category')['Profit'].sum().sort_values(ascending=False)
print("\nCategory-wise Profit:")
print(category_profit)

region_sales = df.groupby('Region')['Total_Sales'].sum().sort_values(ascending=False)
print("\nRegion-wise Sales:")
print(region_sales)

region_profit = df.groupby('Region')['Profit'].sum().sort_values(ascending=False)
print("\nRegion-wise Profit:")
print(region_profit)

segment_sales = df.groupby('Customer_Segment')['Total_Sales'].sum().sort_values(ascending=False)
print("\nCustomer Segment-wise Sales:")
print(segment_sales)

segment_profit = df.groupby('Customer_Segment')['Profit'].sum().sort_values(ascending=False)
print("\nCustomer Segment-wise Profit:")
print(segment_profit)

discount_profit = df.groupby('Discount_Percent')['Profit'].sum().sort_values(ascending=False)
print("\nDiscount-wise Profit:")
print(discount_profit)

payment_sales = df.groupby('Payment_Method')['Total_Sales'].sum().sort_values(ascending=False)
print("\nPayment Method-wise Sales:")
print(payment_sales)

payment_profit = df.groupby('Payment_Method')['Profit'].sum().sort_values(ascending=False)
print("\nPayment Method-wise Profit:")
print(payment_profit)

monthly_sales = df.groupby(
    df['Order_Date'].dt.to_period('M')
)['Total_Sales'].sum()
print("\nMonthly Sales:")
print(monthly_sales)

plt.figure(figsize=(12, 6))
plt.plot(monthly_sales.index.astype(str), monthly_sales.values, marker='o')
plt.title('Monthly Sales Trend')
plt.xlabel('Month')
plt.ylabel('Total Sales')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
plt.bar(category_sales.index, category_sales.values)
plt.title('Sales by Product Category')
plt.xlabel('Product Category')
plt.ylabel('Total Sales')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
plt.bar(category_profit.index, category_profit.values)
plt.title('Profit by Product Category')
plt.xlabel('Product Category')
plt.ylabel('Total Profit')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
plt.bar(region_sales.index, region_sales.values)
plt.title('Sales by Region')
plt.xlabel('Region')
plt.ylabel('Totale Sales')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10,6))
plt.bar(region_profit.index,region_profit.values)
plt.title('Profit by Region')
plt.xlabel('Region')
plt.ylabel('Total Profit')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
plt.bar(segment_sales.index,segment_sales.values)
plt.title('Sales by Customer segment')
plt.xlabel('Customer Segment')
plt.ylabel('TOtal Sales ')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
plt.bar(segment_profit.index, segment_profit.values)
plt.title('Profit by Customer Segment')
plt.xlabel('Customer Segment')
plt.ylabel('Total Profit')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
plt.bar(payment_sales.index, payment_sales.values)
plt.title('Sales by Payment Method')
plt.xlabel('Payment Method')
plt.ylabel('Total Sales')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

print(df.columns.tolist())
top_products = df.groupby('Product_Name')['Total_Sales'].sum().sort_values(ascending=False).head(10)
plt.figure(figsize=(10, 6))
plt.barh(top_products.index, top_products.values)
plt.title('Top 10 Products by Sales')
plt.xlabel('Total Sales')
plt.ylabel('Product Name')
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()


top_profit_products = df.groupby('Product_Name')['Profit'].sum().sort_values(ascending=False).head(10)
plt.figure(figsize=(10, 6))
plt.barh(top_profit_products.index, top_profit_products.values)
plt.title('Top 10 Products by Profit')
plt.xlabel('Total Profit')
plt.ylabel('Product Name')
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

region_analysis = df.groupby('Region')[['Total_Sales', 'Profit']].sum()
region_analysis.plot(kind='bar', figsize=(9, 6))
plt.title('Sales vs Profit by Region')
plt.xlabel('Region')
plt.ylabel('Amount')
plt.xticks(rotation=0)
plt.legend(['Sales', 'Profit'])
plt.tight_layout()
plt.show()

print(df.columns.tolist())
category_analysis = df.groupby('Product_Category')[['Total_Sales', 'Profit']].sum()
category_analysis.plot(kind='bar', figsize=(9, 6))
plt.title('Sales vs Profit by Category')
plt.xlabel('Category')
plt.ylabel('Amount')
plt.xticks(rotation=0)
plt.legend(['Sales', 'Profit'])
plt.tight_layout()
plt.show()

avg_discount_profit = df.groupby('Discount_Percent')['Profit'].mean()

plt.figure(figsize=(10, 6))
plt.plot([f"{d}%" for d in avg_discount_profit.index], avg_discount_profit.values, marker='o', color='crimson', linewidth=2)

plt.title('Impact of Discount on Average Profit')
plt.xlabel('Discount Percentage')
plt.ylabel('Average Profit per Order ($)')

plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()